### ISSUE TITLE
粘贴时清除格式

### ISSUE THREAD

**Issue by kwokpia** [openai-translator/bob-plugin-openai-translator#101]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

2.2.0

### 系统版本 | System version

14

### Bob version

1.8.2

### 复现步骤 | Reproduce step

<img width="464" alt="截屏2023-12-02 07 42 51" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/2770733/6c8c4387-8401-40fd-87e5-0b27030c559f">

### 你看到了什么错误？What errors do you see?

粘贴时没清理富文本格式

### 你期望看到什么？What did you expect to see?

清理富文本格式

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
1. 这是 Bob 实现的问题，与插件无关
2. 带格式的文本输入不会影响插件解析和使用
3. macOS 想粘贴纯文本时，使用 Shift + Command + V 快捷键

**Comment by kwokpia** [comment]
感谢回复发自我的 iPhone在 2023年12月2日，10:32，Bryan Lee ***@***.***> 写道：﻿
Closed #101 as completed.
