### ISSUE TITLE
[Bug] Azure Open AI 的验证功能失效

### ISSUE THREAD

**Issue by JiyuShao** [openai-translator/bob-plugin-openai-translator#102]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

2.2.0

### 系统版本 | System version

macOS 12.2.1

### Bob version

Bob 1.8.2 [148]

### 复现步骤 | Reproduce step

使用 Azure OpenAI，配置完成后点击验证出错，但是保存后能正常使用

### 你看到了什么错误？What errors do you see?

<img width="421" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/6871513/a8f57aad-609c-45ed-ab94-c339dd122efb">

### 你期望看到什么？What did you expect to see?

验证的逻辑应该与正常使用的逻辑相同，失败与成功的表现一致

### 还有其他的内容吗？Anything else?

验证的时候请求了 https://xxx.openai.azure.com/v1/models 接口，返回结果如下：
{"error":{"code":"404","message": "Resource not found"}}

<img width="898" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/6871513/84ccf985-6cbb-4736-ae0e-8770053e75c5">

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
试试 https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.2.1

**Comment by JiyuShao** [comment]
验证的还是报错：
<img width="418" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/6871513/5641952f-eb09-4d57-a4b2-860aac1a94ef">

![image](https://github.com/openai-translator/bob-plugin-openai-translator/assets/6871513/73a83726-3c55-41c6-872e-21aa2f6f5ea2)

正常的请求如下：
![image](https://github.com/openai-translator/bob-plugin-openai-translator/assets/6871513/70d29ea3-1fb2-427b-a57f-f13e9e3b40aa)

**Comment by liby** [comment]
又更新了一版，https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.2.2

**Comment by JiyuShao** [comment]
一样的问题，应该是 POST Body 的格式不对
https://github.com/openai-translator/bob-plugin-openai-translator/blob/v2.2.2/src/main.js#L366

Body 下面这个格式是失败的：
`{"max_tokens":5,"prompt":"Once upon a time"}`

Body 下面这个格式是成功的：
`{"stream":true,"messages":[{"content":"You are a translation engine that can only translate text and cannot interpret it.","role":"system"},{"content":"translate from en to zh-Hans:\n\nOnce upon a time","role":"user"}],"frequency_penalty":1,"model":"gpt-3.5-turbo-16k","temperature":0.20000000000000001,"presence_penalty":1,"top_p":1,"max_tokens":1000}`

**Comment by liby** [comment]
挺奇怪的，我是看着官方的 Example 是这样写的
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/examples/completions.json#L9

**Comment by JiyuShao** [comment]
> 挺奇怪的，我是看着官方的 Example 是这样写的 https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/examples/completions.json#L9

- 这个是 completion 的示例，[Completions API](https://platform.openai.com/docs/guides/text-generation/completions-api) 已经过时了
- 代码里用的是 chat completion 的接口，所以应该参考这个 [Example](https://github.com/Azure/azure-rest-api-specs/blob/main/specification/cognitiveservices/data-plane/AzureOpenAI/inference/stable/2023-05-15/examples/chat_completions.json)

**Comment by liby** [comment]
已经更新了 https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.2.3

**Comment by JiyuShao** [comment]
可以了
