### ISSUE TITLE
有考虑支持 gemini pro 模型吗

### ISSUE THREAD

**Issue by zhaodezhen** [openai-translator/bob-plugin-openai-translator#103]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

可以增加 Gemini 模型吗

### 描述 Motivation

谷歌新一代AI：Gemini发布有一段日子了，免费1分钟能调用60次，很慷慨

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
如果有很多人需要的话，可以考虑支持
