### ISSUE TITLE
[Feature] “prompt好像有些问题，没有明确指示语言”

### ISSUE THREAD

**Issue by folook** [openai-translator/bob-plugin-openai-translator#104]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

需要修改 UserPrompt

### 描述 Motivation

 以汉译英为例，我尝试打印出了发给 openai 的 prompt：最终 UserPrompt 是: translate from zh-Hans to en:\n\n整理好的落叶松就要被履带拖拉机拖走了

### Solution

 是否考虑将 prompt 中的语言代码zh-Hans 和 en 改为 Chinese 和 English，即最终的 UserPrompt : translate from Chinese to English

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
这样会有什么问题吗？
<img width="435" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/14965e90-d15e-4ae1-8684-85db21ae8510">
