### ISSUE TITLE
[Bug] 显示接口相应错误，请问是什么原因呀？

### ISSUE THREAD

**Issue by diudiu121212** [openai-translator/bob-plugin-openai-translator#105]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

gpt-3.5-turbo

### 系统版本 | System version

macOS 14.2.1 (23C71)

### Bob version

Bob 1.8.2[148] 

### 复现步骤 | Reproduce step

当我进行化词翻译时，会出现图片上的情况。
<img width="348" alt="截屏2024-01-14 17 25 58" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/156574069/d273bfd1-21ab-49b6-9b44-5301f402662d">

### 你看到了什么错误？What errors do you see?

显示接口相应错误

### 你期望看到什么？What did you expect to see?

期望能成功翻译

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
截图不是写的挺清楚的吗？

https://platform.openai.com/account/limits

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/issues/106#issuecomment-1912973918
