### ISSUE TITLE
总是提示请求频繁是为什么呢

### ISSUE THREAD

**Issue by Mamba243** [openai-translator/bob-plugin-openai-translator#106]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

2.2.3

### 系统版本 | System version

macos14.2.1

### Bob version

bob 1.8.2[148]

### 复现步骤 | Reproduce step

我按要求输入了openai自己账户的key，但是提示总是提示 接口响应错误 - 请求过于频繁，请慢一点。OpenAI 对您在 API 上的请求实施速率限制。这些限制适用于每分钟 tokens 数、每分钟请求数（某些情况下是每天请求数）。访问 https://platform.openai.com/account/rate-limits 了解更多信息，或参考 OpenAI 模型的默认速率限制

### 你看到了什么错误？What errors do you see?

接口响应错误 - 请求过于频繁，请慢一点。OpenAI 对您在 API 上的请求实施速率限制。这些限制适用于每分钟 tokens 数、每分钟请求数（某些情况下是每天请求数）。访问 https://platform.openai.com/account/rate-limits 了解更多信息，或参考 OpenAI 模型的默认速率限制

### 你期望看到什么？What did you expect to see?

希望能正常使用

### 还有其他的内容吗？Anything else?

我的帐户是免费的帐户，openai3.5，在官网能正常对话，但在插件却用不了，该插件是否需要自己的帐户开通4.0才可用？

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
官网是官网，API 是 API，API 需要账户有余额才能用
<img width="749" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/b1343572-d6de-4a3d-b484-04a2f4be6c4a">

**Comment by Mamba243** [comment]
感谢解答！原来如此，祝愿插件越来越强大




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "openai-translator/bob-plugin-openai-translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月27日(星期六) 中午11:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [openai-translator/bob-plugin-openai-translator] 总是提示请求频繁是为什么呢 (Issue #106)





 
官网是官网，API 是 API，API 需要账户有余额才能用
 image.png (view on web)

**Comment by liby** [comment]
感谢反馈，这其实也是 OpenAI 在账户 API Credits 不可用的情况仍返回 429 Too Many Requests 造成的误解。

为了避免更多的插件使用者被误解，我已经更新了 https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.2.4 ，增加了说明信息，希望能带来一些改善

<img width="409" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/a5bddef9-5cf3-4ac3-8caf-45b8b53f02da">
