### ISSUE TITLE
[Feature] TTS Support

### ISSUE THREAD

**Issue by zhuozhiyongde** [openai-translator/bob-plugin-openai-translator#107]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

如题，增加语音合成的 OpenAI 服务

### 描述 Motivation

现有的朗读服务效果都不太好，不如 OpenAI TTS

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [x] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by zhuozhiyongde** [comment]
我有意为此功能提交 PR，但是近期可能没时间，最早可能也得五一假期了，如果大佬能在那之前实现的话那就当我没说，不然的话我就在五一研究一下，刚才看了眼文档似乎不是很复杂，拿到返回的 mp3 然后 base64 编码一下就行，估计要取消一下流式返回（？

**Comment by liby** [comment]
bob-plugin-openai-translator 是 Bob 的文本翻译插件，你说是应该是 Bob 的语音合成插件，不应该在这个仓库里实现
