### ISSUE TITLE
[Bug] 请问使用转化的openai接口，API URL里应该填什么?

### ISSUE THREAD

**Issue by GoTop** [openai-translator/bob-plugin-openai-translator#109]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

2.2.4

### 系统版本 | System version

macOS  14.1.2 (23B92)

### Bob version

1.9.2

### 复现步骤 | Reproduce step

我在API URL里填写 http://localhost:7077 或者 http://localhost:7077/v1/  或者  http://localhost:7077/v1/chat/completions 都无法验证成功，请问该填什么样的url呢

这个本机上运行的openai服务是可以正常使用的

我在“openai 自定义”插件里，将“自定义API URL”设置为http://localhost:7077/v1/chat/completions ，也是可以正常使用的

### 你看到了什么错误？What errors do you see?

点击“验证”，提示验证失败

### 你期望看到什么？What did you expect to see?

希望通过验证

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
多谢反馈，实际上这个验证功能的初衷是给提供使用 OpenAI 官方 API 或者 Azure OpenAI Service 的用户使用的。

对于 OpenAI 官方 API：
- 调用 `https://api.openai.com/v1/models` 并传递 API Key，观察 API Response

对于 Azure OpenAI Service
- 调用 `https://openai.azure.com/openai/deployments/${deploymentName}/chat/completions?api-version=2023-05-15` 并传递最简单的 messages 参数，观察 API Response

因此如果你的翻译功能正常可用，可以不用理会这个验证的返回结果。我回头更新一下文档，说明一下这一点

**Comment by GoTop** [comment]
> 多谢反馈，实际上这个验证功能的初衷是给提供使用 OpenAI 官方 API 或者 Azure OpenAI Service 的用户使用的。
> 
> 对于 OpenAI 官方 API：
> 
> * 调用 `https://api.openai.com/v1/models` 并传递 API Key，观察 API Response
> 
> 对于 Azure OpenAI Service
> 
> * 调用 `https://openai.azure.com/openai/deployments/${deploymentName}/chat/completions?api-version=2023-05-15` 并传递最简单的 messages 参数，观察 API Response
> 
> 因此如果你的翻译功能正常可用，可以不用理会这个验证的返回结果。我回头更新一下文档，说明一下这一点

那请问在API URL里， 应该填写 http://localhost:7077/ 或者 http://localhost:7077/v1/ 或者 http://localhost:7077/v1/chat/completions ？ 还是http://localhost:7077/v1/models 呢？

**Comment by liby** [comment]
因为不清楚你在本地运行的什么模型，所以没法直接给出答案。

作为参考，我在使用 OpenAI 官方的 API 时，只需要填入 `https://api.openai.com` 就可以了
