### ISSUE TITLE
希望支持自定义model name，能适配moonshot api key

### ISSUE THREAD

**Issue by shibing624** [openai-translator/bob-plugin-openai-translator#110]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

希望支持自定义model name，能适配moonshot api key

### 描述 Motivation

希望支持自定义模型名称，这样国内类似暗面的api也能用了，它们都是跟openai的api结构一样，可以复用openai的请求方法，填好对应的api base url 和api key就可以，再改下model name就能适配。    https://platform.moonshot.cn/console/api-keys

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
[已经支持了](https://github.com/openai-translator/bob-plugin-openai-translator/blob/main/docs/configuration_manual_CN.md#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A8%A1%E5%9E%8B)

**Comment by shibing624** [comment]
好吧，看到了，商店版支持了，我安装的是之前的社区版。
