### ISSUE TITLE
请支持Ollama谢谢

### ISSUE THREAD

**Issue by toyo2333** [openai-translator/bob-plugin-openai-translator#116]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

支持Ollama使用gemma2 和 qwen2 谢谢

### 描述 Motivation

自己电脑上部署自己用。

### Solution

自己电脑上部署自己用。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
你将 bob-plugin-openai-translator 做如下设置试试看：

<img width="455" alt="image" src="https://github.com/user-attachments/assets/032356b6-1c91-4b9e-b6bd-960bc5629e54">

我本身没有用 Ollama，是从 Ollama 官方文档看到是[兼容 OpenAI 的](https://ollama.com/blog/openai-compatibility)
