### ISSUE TITLE
[Bug] “2.4.0版本号不一致”

### ISSUE THREAD

**Issue by Yz-Crazy** [openai-translator/bob-plugin-openai-translator#119]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

2.4.0

### 系统版本 | System version

mac

### Bob version

1.10.0

### 复现步骤 | Reproduce step

1、打开检查更新
2、更新

### 你看到了什么错误？What errors do you see?

该插件升级安装包 info.json 中的 version 与 appcast 文件中的 version 不一致。

安装包的 version：2.3.2
appcast 中的 version：2.4.0

手动下载2.4.0 清理2.3.2 安装之后也是显示2.3.2 版本
![CleanShot 2024-08-07 at 16 35 24](https://github.com/user-attachments/assets/a42f5747-2c52-4b36-8a7f-55b87844e482)

### 你期望看到什么？What did you expect to see?

更新完成

### 还有其他的内容吗？Anything else?

把2.4.0 的包打开查看了 info.json，里面的 version 版本没有改成2.4.0，而是2.3.2
![CleanShot 2024-08-07 at 16 35 04](https://github.com/user-attachments/assets/523c697e-cc88-4caa-a0f5-0e74a7e02bfb)

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.4.2
