### ISSUE TITLE
[Feature] Claude支持

### ISSUE THREAD

**Issue by s-leeq** [openai-translator/bob-plugin-openai-translator#120]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

请问有将浏览器插件版里支持的Claude等移植到Bob插件的计划吗？

### 描述 Motivation

由于现在主要用的都是Claude的API，看到浏览器插件版里有支持，但是Bob插件版的却没有，想请问一下作者有同步的计划吗？

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
手头没有 Claude 的 API，要不你看看 https://github.com/jtsang4/bob-plugin-claude-translator 能否满足需求，这个插件是其作者基于我上一版代码做的修改

**Comment by s-leeq** [comment]
> 手头没有 Claude 的 API，要不你看看 https://github.com/jtsang4/bob-plugin-claude-translator 能否满足需求，这个插件是其作者基于我上一版代码做的修改

简单测试下来没什么问题，感谢！

**Comment by fredericky123** [comment]
想问下现在有新的实现吗 https://github.com/jtsang4/bob-plugin-claude-translator  已经停止维护，在最新版bob上无法使用，安装后不会显示在 服务 里 非常需要一个支持claude api的插件 搜遍了平台 发现一个都没有

**Comment by liby** [comment]
Bob 官方内置服务中已经有 Claude 了可以尝试下

**Comment by fredericky123** [comment]
但是那个是指向官方网址，需要指向第三方中转网址，好像不能修改
