### ISSUE TITLE
Hope to increase stream mode

### ISSUE THREAD

**Issue by iofu728** [openai-translator/bob-plugin-openai-translator#15]
Thank you to the developers for their work. This is a very meaningful tool!
However, it was found that it was not as fast in the process as the turbo API previously used. After referring to the implementation of other tools, like https://github.com/ddiu8081/chatgpt-demo/blob/main/src/pages/api/generate.ts#L26 and https://platform.openai.com/docs/api-reference/completions/create#completions/create-stream, it was found that they had enabled stream mode.
I do not know if it is possible to increase stream mode. Thank you.

**Comment by yetone** [comment]
Thank you for your suggestion. It's my first time hearing about stream mode, and I'm going to look into it now!

**Comment by yetone** [comment]
Just to confirm, are you currently using the `gpt-3.5-turbo` model?
<img width="210" alt="image" src="https://user-images.githubusercontent.com/1206493/222754844-0fcd3f7b-c8ea-4f96-b090-c4cef0ba5a61.png">

**Comment by iofu728** [comment]
Yeah, I use the gpt-3.5-turbo. If I translate more than 1k tokens, It'll take more than 10s too.

**Comment by Ukenn2112** [comment]
Bob currently does not support stream. You can follow this issue for updates.

https://github.com/ripperhe/Bob/issues/451

**Comment by iofu728** [comment]
> Bob currently does not support stream. You can follow this issue for updates.
> 
> [ripperhe/Bob#451](https://github.com/ripperhe/Bob/issues/451)

Thank you for the information.

**Comment by fredericky123** [comment]
好像官方的bob实现了stream功能
咱们这款插件能否实现呢

**Comment by Ukenn2112** [comment]
> 好像官方的bob实现了stream功能
> 
> 咱们这款插件能否实现呢

目前只有Bob自带的OpenAi翻译可以使用，并未开放给插件调用。

https://github.com/ripperhe/Bob/issues/451#issuecomment-1500774572

据说后续会开放

**Comment by xieft** [comment]
BOB已支持
https://github.com/ripperhe/Bob/issues/451#issuecomment-1552903333

**Comment by liby** [comment]
> BOB已支持 [ripperhe/Bob#451 (comment)](https://github.com/ripperhe/Bob/issues/451#issuecomment-1552903333)

https://github.com/openai-translator/bob-plugin-openai-translator/issues/15#issuecomment-1554605268

**Comment by liby** [comment]
github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v1.0.0

**Comment by fredericky123** [comment]
请问能关闭stream模式吗

**Comment by liby** [comment]
> 请问能关闭stream模式吗

https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v0.4.1

**Comment by fredericky123** [comment]
> > 请问能关闭stream模式吗
> 
> https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v0.4.1

还是没看懂怎么关闭

**Comment by liby** [comment]
v0.4.1 不支持 stream

**Comment by liby** [comment]
v0.4.1 支持最新的 GPT models，也支持 custom prompts，不支持 stream，还有哪里不满足你的需求？
