### ISSUE TITLE
插件60秒未响应，两个都是

### ISSUE THREAD

**Issue by yaxiingz** [openai-translator/bob-plugin-openai-translator#47]
<img width="392" alt="截屏2023-03-08 17 34 15" src="https://user-images.githubusercontent.com/66823229/223676494-7670995b-8ff0-4e7d-bcb5-ff5a03bd76e1.png">

有人遇到类似的问题吗？

**Comment by zhengdaguang** [comment]
OpenAI Translator  一直转圈，没有翻译结果，之前第一次安装翻译没问题，目前更新的最新版本插件。

**Comment by zhengdaguang** [comment]
我也有同样的问题，最新版本。
<img width="400" alt="image" src="https://user-images.githubusercontent.com/40955943/223959798-b3876321-24e1-4224-b17f-55cef87b347d.png">

**Comment by yaxiingz** [comment]
试了重启之类的方法，还是无法解决

**Comment by hemycoo** [comment]
同样的问题问题，无法解决。。。

**Comment by liby** [comment]
> 我的最近一直出现这个错误信息： 接口响应错误 - You exceeded your current quota, please check your plan and billing details.
> 
> 但是我在openai.com主页确认的我帐号还是可以用的啊。而且我新建个API试了，还是出样出错。

你应该在 https://platform.openai.com/account/usage 查看你的 API 用量，应该会有地方告诉你，你的免费额度已经过期。

另外官方的网页版和 API 是两种使用 GPT 的方式，API 到期不影响网页版的使用。

**Comment by ElvisJcy** [comment]
接口响应错误 - Too Many Requests

已经换了一次api，怎么解决呢？

**Comment by liby** [comment]
> 接口响应错误 - Too Many Requests
> 
> 已经换了一次api，怎么解决呢？

Too Many Requests: 请求过多

<img width="1256" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/db5ad753-fa76-4535-acd9-2775a38e2caa">

https://help.openai.com/en/articles/6843909-rate-limits-and-429-too-many-requests-errors

**Comment by ElvisJcy** [comment]
> https://help.openai.com/en/articles/6843909-rate-limits-and-429-too-many-requests-errors

感谢！

**Comment by yeesumNgai** [comment]
> > 我的最近一直出现这个错误信息： 接口响应错误 - You exceeded your current quota, please check your plan and billing details.
> > 但是我在openai.com主页确认的我帐号还是可以用的啊。而且我新建个API试了，还是出样出错。
> 
> 你应该在 https://platform.openai.com/account/usage 查看你的 API 用量，应该会有地方告诉你，你的免费额度已经过期。
> 
> 另外官方的网页版和 API 是两种使用 GPT 的方式，API 到期不影响网页版的使用。

是不是免费额度到期就不能使用了呀？我刚刚查了一下账户是显示免费额度到期了 哎
