### ISSUE TITLE
一个可以减少翻译用时和免代理的方法

### ISSUE THREAD

**Issue by ithou** [openai-translator/bob-plugin-openai-translator#50]
## 目前此插件的不足❌
1. 需要挂代理
2. 翻译用时比腾讯和有道的API都略长，能达到三五秒左右

## 可以改进的地方 ✅
1. 增加**自定义API**接口的功能。就是这么一个功能，就足以 **免代理** 和 **减少翻译时常**。因为可以使用 Cloudflare Workers来代理 api.openai.com 这个接口域名来实现。
参考：https://github.com/noobnooc/noobnooc/discussions/9#discussioncomment-5239691

**Comment by yetone** [comment]
已经支持自定义 API 的功能

**Comment by ithou** [comment]
> 已经支持自定义 API URL 的功能

感谢🙏 润色那款Bob插件也会更新吗？

**Comment by Erimus-Koo** [comment]
另外建议开启API里的stream参数吧，也就是打字机模式，反馈速度可以显著提高。👍
