### ISSUE TITLE
[Bug] “接口响应错误 - You exceeded your current quota, please check your plan and billing details.”

### ISSUE THREAD

**Issue by MustardWithRice** [openai-translator/bob-plugin-openai-translator#82]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/bob-plugin-openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

0.4.0

### 系统版本 | System version

macos 12.5

### Bob version

0.10.3

### 复现步骤 | Reproduce step

按照步骤添加插件后报错

### 你看到了什么错误？What errors do you see?

接口响应错误 - You exceeded your current quota, please check your plan and billing details.

### 你期望看到什么？What did you expect to see?

应该是翻译之后的文字

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
打开 https://platform.openai.com/account/usage 看一下嘞
