### ISSUE TITLE
接口响应错误 - Too Many Requests

### ISSUE THREAD

**Issue by weilunn** [openai-translator/bob-plugin-openai-translator#85]
### Please search before asking

- [X] I searched in the [issues](https://github.com/yetone/bob-plugin-openai-translator/issues) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

v1.1.0

### 系统版本 | System version

macOS Ventura 13.4

### Bob version

Bob 1.8.0 [122]

### 复现步骤 | Reproduce step

使用本插件翻译/润色时，显示“接口响应错误 - Too Many Requests”。

### 你看到了什么错误？What errors do you see?

“接口响应错误 - Too Many Requests”

### 你期望看到什么？What did you expect to see?

正常翻译/润色

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
> I searched in the [issues](https://github.com/yetone/bob-plugin-openai-translator/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc) and found nothing similar.

https://github.com/openai-translator/bob-plugin-openai-translator/issues/47#issuecomment-1573135854
