### ISSUE TITLE
[Feature] “希望可以增加Azure OpenAl配置功能,在中国使用OpenAl太麻烦了,使用Azure还是很方便的”

### ISSUE THREAD

**Issue by Bravo911** [openai-translator/bob-plugin-openai-translator#86]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

增加Azure OpenAl配置功能

### 描述 Motivation

在中国使用Azure OpenAl的便利性很高,对网络环境也没那么麻烦.
最重要的是我没办法注册到OpenAl,没key.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
<img width="744" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/22e2f051-7cd1-4451-8447-8db0e3e817dc">

现在的版本就以支持，填写 API endpoint 和 Deployment name 就能使用
