### ISSUE TITLE
接口响应错误 - Too Many Requests

### ISSUE THREAD

**Issue by yeesumNgai** [openai-translator/bob-plugin-openai-translator#87]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

v1.1.1

### 系统版本 | System version

macos 12.4

### Bob version

bob 1.8.0

### 复现步骤 | Reproduce step

很久没有用这个插件了，今天用的时候open ai 那一列就没有翻译，显示 接口响应错误 - Too Many Requests，刷新也没有用，然后我重新换了一个apikey也没有用，请问这个该怎么解决呀

### 你看到了什么错误？What errors do you see?

openai窗口显示 接口响应错误 - Too Many Requests

### 你期望看到什么？What did you expect to see?

怎么重新使用

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/issues/85
