### ISSUE TITLE
[Feature] “请问支持gpt 4 8k吗”

### ISSUE THREAD

**Issue by fredericky123** [openai-translator/bob-plugin-openai-translator#90]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

8k 模型全面开放了 看到配置里有32k

### 描述 Motivation

8k 模型全面开放了 看到配置里有32k，请问如何设置为8k的模型

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by fredericky123** [comment]
明明提示都支持8k了，可是配置为gpt 4 或者gpt 4 0613缺显示接口响应错误

**Comment by liby** [comment]
你有访问 GPT-4 的权限吗？

**Comment by fredericky123** [comment]
> 你有访问 GPT-4 的权限吗？
虽然有了支付账单，但还是没有访问权限

**Comment by liby** [comment]
所以就是没有申请到 GPT-4 API 的访问权限对吗？那我先关了
