### ISSUE TITLE
[Feature] Please support LocalAI

### ISSUE THREAD

**Issue by mritd** [openai-translator/bob-plugin-openai-translator#92]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

Please support LocalAI

### 描述 Motivation

> [LocalAI](https://localai.io/) is a drop-in replacement REST API that’s compatible with OpenAI API specifications for local inferencing. 

Is it possible to support using LocalAI as a backend for translation?

### Solution

Adjust API calling method, support custom model.

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
- API URL: `http://localhost:8080/v1`
- Model: `gpt-4`
