### ISSUE TITLE
接口响应错误 - Too Many Requests[Bug] “请输入标题，不要留空 - Please enter a title, do not leave it blank.}}”

### ISSUE THREAD

**Issue by Quans-qiu** [openai-translator/bob-plugin-openai-translator#93]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

1.1.1

### 系统版本 | System version

macOS 13.4.1

### Bob version

1.8.0

### 复现步骤 | Reproduce step

无

### 你看到了什么错误？What errors do you see?

接口响应错误 - Too Many Requests

### 你期望看到什么？What did you expect to see?

API 收费了

### 还有其他的内容吗？Anything else?

无

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/issues/91

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/issues/106#issuecomment-1912973918

为了避免更多的插件使用者被误解，我已经更新了 [v2.2.4 (release)](https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v2.2.4) ，增加了说明信息，希望能带来一些改善
