### ISSUE TITLE
无法正常翻译

### ISSUE THREAD

**Issue by iRubbish** [openai-translator/bob-plugin-openai-translator#94]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

0.4.1

### 系统版本 | System version

13.3.1

### Bob version

0.10.3

### 复现步骤 | Reproduce step

使用翻译的时候

### 你看到了什么错误？What errors do you see?

I'm sorry, but I am unable to determine the source and target languages based on the provided information. Please specify the source language and target language so that I can assist you with the translation.

### 你期望看到什么？What did you expect to see?

翻译

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
给出插件配置页面的截图以及使用插件翻译时出现错误的录屏
