### ISSUE TITLE
[Feature] 请求支持最新的“dall-e-3”、gpt-3.5-turbo-1106，亲测 1106 速度贼快

### ISSUE THREAD

**Issue by lijxse** [openai-translator/bob-plugin-openai-translator#95]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

请求支持最新的“dall-e-3”、gpt-3.5-turbo-1106，亲测 1106 速度贼快

### 描述 Motivation

请求支持最新的“dall-e-3”、gpt-3.5-turbo-1106，亲测 1106 速度贼快。或者干脆让插件支持用户自定义模型名吧。

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [ ] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
https://github.com/openai-translator/bob-plugin-openai-translator/releases/tag/v1.1.3

**Comment by lijxse** [comment]
作者真快~赞~
