### ISSUE TITLE
[Feature] “请问可以支持gpt-3.5-turbo-1106吗”

### ISSUE THREAD

**Issue by notdp** [openai-translator/bob-plugin-openai-translator#97]
### Search before asking

- [X] 在 [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) 中没有找到类似的内容。I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Feature

请问可以支持gpt-3.5-turbo-1106吗

### 描述 Motivation

该模型的速度非常快，并且费率更低   

另外一种可选的方案是支持自定义model          

### 你是否愿意提交一份 PR？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by notdp** [comment]
不好意思 第一次用bob，添加成了openai密钥这个插件了

**Comment by liby** [comment]
对，仓库发布的是这个
<img width="309" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/a7778683-37be-4253-a314-c3e29a65363e">

下面是 Bob 内置的
<img width="302" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/efce67ba-19b9-4f2a-aaf8-b205d13bce7d">

区别可以参考 Bob 的[官方文档](https://bobtranslate.com/blog/2023-05-18-180-plugin.html#tip)，我认为挺可观的：
<img width="807" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/ce1ef719-7a9f-4a2b-b993-215110e4f148">
