### ISSUE TITLE
[Bug]  Use Azure OpenAI service got error message "接口未返回结果" in Bob application window

### ISSUE THREAD

**Issue by mashihua** [openai-translator/bob-plugin-openai-translator#99]
### Please search before asking

- [X] I searched in the [issues](https://github.com/openai-translator/bob-plugin-openai-translator/issues?q=is%3Aissue+sort%3Aupdated-desc+) and found nothing similar.

### Please read README

- [X] I have read the usage instructions section in README in detail.

### Please check your network and OpenAI API quota

- [X] I am sure it is not a network issue or an OpenAI API quota issue.

### OpenAI Translator Bob Plugin version

v2.0.0

### 系统版本 | System version

MacOS 14.1 

### Bob version

Bob 1.8.1 [148]

### 复现步骤 | Reproduce step

Configurations for Azure OpenAI have been set in Bob setting, but when opening the translation window and inputting text for translation, an '接口未返回结果' error occurred. It seems like there is an issue with the handleResponse function in main.js.

### 你看到了什么错误？What errors do you see?

接口未返回结果

### 你期望看到什么？What did you expect to see?

The application translate success

### 你是否愿意提交一份 PR 来修改这个错误？Are you willing to submit a PR?

- [X] 我愿意提供 PR! I'm willing to submit a PR!

**Comment by liby** [comment]
Can you try `2023-03-15-preview`?
<img width="468" alt="image" src="https://github.com/openai-translator/bob-plugin-openai-translator/assets/38807139/e92490e5-667a-4ea1-b53e-58e68ac179b6">

**Comment by cavalleria** [comment]
I have also encountered the same problem when use gpt-3.5-turbo

**Comment by liby** [comment]
> I have also encountered the same problem when use gpt-3.5-turbo

https://github.com/openai-translator/bob-plugin-openai-translator/issues/99#issuecomment-1805084878
